ClaranetCadastro/Models/DBCt.cs
using Microsoft.EntityFrameworkCore;

namespace ClaranetCadastro.Models
{
    public class DBCt : DbContext
    {
        protected readonly IConfiguration Configuration;

        public DBCt(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        protected override void OnConfiguring(DbContextOptionsBuilder options)
        {
            // connect to sql server with connection string from app settings
            options.UseSqlServer(Configuration.GetConnectionString("claranet"));
        }
        

        public DbSet<Empresas> Empresas { get; set; }


        protected override void OnModelCreating (ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.ApplyConfigurationsFromAssembly(typeof(DBCt).Assembly);
        }
    }
}

ClaranetCadastro/Models/Empresas.cs
namespace ClaranetCadastro.Models
{
    public class Empresas
    {
        public int IdEmpresas { get; set; }
        public string CNPJ { get; set; }
        public string RazaoSocial { get; set; }
        public string NomeFantasia { get; set; }
        public string Email { get; set; }
        public string? Telefone { get; set; }
        public string? TelefoneComercial { get; set; }
        public string? Celular { get; set; }
        public string Logradouro { get; set; }
        public int Numero { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string CEP { get; set; }
        public string NomeContato { get; set; }
    }
}

ClaranetCadastro/Models/ErrorViewModel.cs
namespace ClaranetCadastro.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ClaranetCadastro/Models/Login.cs
namespace ClaranetCadastro.Models
{
    public class Login
    {
        public string Usuario { get; set; }
        public string Senha { get; set; }
    }
}

ClaranetCadastro/Controllers/EmpresasController.cs
using ClaranetCadastro.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ClaranetCadastro.Controllers
{
    public class EmpresasController : Controller
    {
        //     private DBCt Context { get; }

        //     public EmpresasController(DBCt _context)
        //     {
        //_context = Context;
        //     }

        public IActionResult IndexEmpresas()
        {
            List<Empresas> empresas = new List<Empresas>();

            //using (var dataContext = new DBCt())
            //{
            //	empresas = dataContext.Empresas.ToList();
            //}
            return View(empresas);
        }

        public IActionResult CadastroEmpresas(int? IdEmpresas)
        {
            var empresas = new Empresas();
            if (IdEmpresas != null)
            {
                //using (var dataContext = new DBCt())
                //{
                //	empresas = dataContext.Empresas.Find(x => x.IdEmpresas == IdEmpresas).FirstOrDefault();
                //}
            }
            return View();
        }

        public IActionResult Cadastro(Empresas cadEmpresa)
        {
            var mensagem = string.Empty;

            if (String.IsNullOrEmpty(cadEmpresa.RazaoSocial) || String.IsNullOrEmpty(cadEmpresa.NomeFantasia) || String.IsNullOrEmpty(cadEmpresa.CNPJ))
                mensagem += "Preencha o todos os dados básicos\n";
            else if (ValidaCnpj(cadEmpresa.CNPJ))
                mensagem += "CNPJ Inválido\n";

            if (String.IsNullOrEmpty(cadEmpresa.Email))
                mensagem += "Preencha o campo de e-mail\n";

            if (String.IsNullOrEmpty(cadEmpresa.NomeContato))
                mensagem += "Preencha o nome do contato\n";

            if (String.IsNullOrEmpty(cadEmpresa.Telefone) && String.IsNullOrEmpty(cadEmpresa.TelefoneComercial) && String.IsNullOrEmpty(cadEmpresa.Celular))
                mensagem += "Preencha ao menos um número para contato\n";

            if (String.IsNullOrEmpty(cadEmpresa.CEP))
                mensagem += "Preencha o campo de CEP\n";

            if (String.IsNullOrEmpty(mensagem))
                return RedirectToAction("CadastroEmpresas", cadEmpresa);
            else
            {
                try
                {
                    //using (var dataContext = new DBCt())
                    //{
                    //	dataContext.Empresas.Add(cadEmpresa);
                    //  dataContext.SaveChanges();
                    //}

                }
                catch (Exception ex)
                {

                }

                return RedirectToAction("IndexEmpresas");
            }
        }

        public static bool ValidaCnpj(string cnpj)
        {
            int[] multiplicador1 = new int[12] { 5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2 };
            int[] multiplicador2 = new int[13] { 6, 5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2 };
            int soma;
            int resto;
            string digito;
            string tempCnpj;

            cnpj = cnpj.Trim();
            cnpj = cnpj.Replace(".", "").Replace("-", "").Replace("/", "");

            if (cnpj.Length != 14)
                return false;

            tempCnpj = cnpj.Substring(0, 12);

            soma = 0;
            for (int i = 0; i < 12; i++)
                soma += int.Parse(tempCnpj[i].ToString()) * multiplicador1[i];

            resto = (soma % 11);
            if (resto < 2)
                resto = 0;
            else
                resto = 11 - resto;

            digito = resto.ToString();

            tempCnpj = tempCnpj + digito;
            soma = 0;
            for (int i = 0; i < 13; i++)
                soma += int.Parse(tempCnpj[i].ToString()) * multiplicador2[i];

            resto = (soma % 11);
            if (resto < 2)
                resto = 0;
            else
                resto = 11 - resto;

            digito = digito + resto.ToString();

            return cnpj.EndsWith(digito);
        }

        public IActionResult ExcluiCadastroEmpresas(int IdEmpresas)
        {
            try
            {
                //using (var dataContext = new DBCt())
                //{
                //	empresas = dataContext.Empresas.Find(x => x.IdEmpresas == IdEmpresas).FirstOrDefault();
                //}
            }catch(Exception ex)
            {

            }

            return View();
        }
    }
}

ClaranetCadastro/Controllers/HomeController.cs
using ClaranetCadastro.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ClaranetCadastro.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ClaranetCadastro/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace ClaranetCadastro.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }

        public IActionResult ValidacaoLogin(Models.Login login)
        {
            return RedirectToAction("Index", "Home");
        }
    }
}

ClaranetCadastro/Views/Empresas/CadastroEmpresas.cshtml
@model Empresas
@{
    ViewData["Title"] = "Cadastro de Empresa";
}

<div class="text-center">
    <h1 class="display-4">Cadastro</h1>
    <hr />
    <form asp-controller="Empresas" asp-action="Cadastro">
        <input type="hidden" name="cadEmpresa.IdEmpresas" value="@Model?.IdEmpresas" />

        <div style="border:solid 1px black;align-content:flex-start">
            <h3>Dados básicos</h3>

            <p>CNPJ</p>
            <input type="text" name="cadEmpresa.CNPJ" value="@Model?.CNPJ" id="cnpj" />

            <p>RazaoSocial</p>
            <input type="text" name="cadEmpresa.RazaoSocial" value="@Model?.RazaoSocial" />

            <p>NomeFantasia</p>
            <input type="text" name="cadEmpresa.NomeFantasia" value="@Model?.NomeFantasia" />
        </div>

        <div style="border:solid 1px black;">
            <h3>Dados de Contato</h3>

            <p>NomeContato</p>
            <input type="text" name="cadEmpresa.NomeContato" value="@Model?.NomeContato" />

            <p>Email</p>
            <input type="email" name="cadEmpresa.Email" value="@Model?.Email" />

            <p>Telefone</p>
            <input type="tel" name="cadEmpresa.Telefone" value="@Model?.Telefone" id="telefone" />

            <p>TelefoneComercial</p>
            <input type="tel" name="cadEmpresa.TelefoneComercial" value="@Model?.TelefoneComercial" id="telefoneComercial" />

            <p>Celular</p>
            <input type="tel" name="cadEmpresa.Celular" value="@Model?.Celular" />
        </div>

        <div style="border:solid 1px black;">
            <h3>Dados de Endereço</h3>

            <p>CEP</p>
            <input type="text" name="cadEmpresa.CEP" value="@Model?.CEP" id="cep" />

            <p>Logradouro</p>
            <input type="text" name="cadEmpresa.Logradouro" value="@Model?.Logradouro" />

            <p>Numero</p>
            <input type="number" name="cadEmpresa.Numero" value="@Model?.Numero" />

            <p>Complemento</p>
            <input type="text" name="cadEmpresa.Complemento" value="@Model?.Complemento" />

            <p>Bairro</p>
            <input type="text" name="cadEmpresa.Bairro" value="@Model?.Bairro" />

            <p>Cidade</p>
            <input type="text" name="cadEmpresa.Cidade" value="@Model?.Cidade" />

            <p>Estado</p>
            <input type="text" name="cadEmpresa.Estado" value="@Model?.Estado" />
        </div>

        <input type="submit" />
    </form>
</div>

ClaranetCadastro/Views/Empresas/IndexEmpresas.cshtml
@{
    ViewData["Title"] = "Empresas";
}
@model List<Empresas>


<div>
    @*<input type="button" name="Cadastro" id="CadastroEmpresa" />*@
    <input type="button" onclick="@(Url.Action("CadastroEmpresas", "Empresas"))" />
     

    <table cellpadding="0" cellspacing="0" style="border:solid black 1px ">
        <tr>
            <th>Edit</th>
            <th>CNPJ</th>
            <th>RazaoSocial</th>
            <th>NomeContato</th>
        </tr>
        @foreach (Empresas empresas in Model)
        {
            <tr>
                <td><a asp-area="" asp-controller="Empresas" asp-action="CadastroEmpresas" asp-route-IdEmpresas="@empresas.IdEmpresas">Editar</a></td>
                <td>@empresas.CNPJ</td>
                <td>@empresas.RazaoSocial</td>
                <td>@empresas.NomeContato</td>
            </tr>
        }
    </table>

</div>

ClaranetCadastro/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ClaranetCadastro/Views/Login/Login.cshtml
@{
    Layout = "";
    ViewData["Title"] = "LoginView";
}
@model Login


<div>
    <form asp-controller="Login" asp-action="ValidacaoLogin">
        <h1>Login</h1>
        <p>usuario</p>
        <input type="text" name="login.usuario"/>
        <p>senha</p>
        <input type="password" name="login.senha" />
        <input type="submit" />
        
    </form>
</div>

ClaranetCadastro/Views/Shared/_Layout.cshtml
@inject IConfiguration configuration

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Claranet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ClaranetCadastro.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ClaranetCadastro</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empresas" asp-action="IndexEmpresas">Empresas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Claranet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>